### PR TITLE
Analytics deps optimisation

### PR DESCRIPTION
**Pull request by jonyrock**
We have a lot of deps in analytics/requirements.txt,  which we don't really use.

Closes https://github.com/hastic/hastic-server/issues/540

It saves about 100M in [site-packages](https://docs.python.org/3.6/install/) folder. 

Doesn't affect to the bundle size made by PyInstaller.

### CODE REVIEW

**Comment by jonyrock** [comment]
@rozetko I am not sure about `python -m PyInstaller --paths=analytics/ --additional-hooks-dir=pyinstaller_hooks bin/server` command now, can I ask you to check please?

**Comment by rozetko** [comment]
@jonyrock guess we should've left `sklearn` hook
Guess it's a dependency of some lib
I'll check it

**Comment by jonyrock** [comment]
@rozetko we don't have `sklearn` in deps of our deps

**Comment by jonyrock** [comment]
```
aiounittest
aiounittest-1.1.0.dist-info
altgraph
altgraph-0.16.1.dist-info
attrdict
attrdict-2.0.0.egg-info
dateutil
easy_install.py
future
future-0.17.1.egg-info
libfuturize
libpasteurize
macholib
macholib-1.11.dist-info
numpy
numpy-1.14.5.dist-info
ordlookup
pandas
pandas-0.20.3.dist-info
past
pefile-2018.8.8.egg-info
pefile.py
peutils.py
pip
pip-19.0.3.dist-info
pkg_resources
pkg_resources-0.0.0.dist-info
__pycache__
PyInstaller
PyInstaller-3.4.egg-info
python_dateutil-2.8.0.dist-info
pytz
pytz-2019.1.dist-info
pyzmq-18.0.1.dist-info
scipy
scipy-1.1.0.dist-info
setuptools
setuptools-20.7.0.dist-info
six-1.12.0.dist-info
six.py
zmq
```

this is what what you make a clear virtualenv and then do `pip install -r requirements.txt` and everything necessary for testing and building from source

**Comment by rozetko** [comment]
@jonyrock I checked `pyinstaller` command, it works (builds and runs)
Current `dist` size is 174MB
Previous size - 193MB

**Pull request merged**
