### PR TITLE
WIP: Websocket connectivity between server and analytics

### LINKED ISSUE #753: Node 11 build
It is a piece of log during build:

```
                                     ^
/home/alex/.node-gyp/11.15.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../binding.cc:40:0:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1034:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from ../binding.cc:24:0:
/home/alex/.node-gyp/11.15.0/include/node/v8.h:10251:15: note: declared here
 Local<String> Value::ToString() const {
               ^
In file included from ../binding.cc:40:0:
../../nan/nan.h:1044:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/alex/.node-gyp/11.15.0/include/node/v8.h:26:0,
                 from ../binding.cc:24:
/home/alex/.node-gyp/11.15.0/include/node/v8.h:2754:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/home/alex/.node-gyp/11.15.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../binding.cc: In member function ‘void zmq::Socket::NotifyReadReady()’:
../binding.cc:394:73: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(this->handle(), callback_v.As<Function>(), 0, NULL);
                                                                         ^
In file included from ../binding.cc:40:0:
../../nan/nan.h:929:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^
```

### PR DESCRIPTION
**Pull request by jonyrock-back**
It's hard to support zmq on node.js side because of many reasons.
last version [zeromq.js](https://github.com/zeromq/zeromq.js/) supports only Node.js v.10.2+

all debug / production connectivity is removed and only websocket connection is available.

It fixes #753, #812 and #852 (closing port part)

### Server
* remove `zeromq` dependency from `server/package.json`
* add dependency to [websockets/ws](https://github.com/websockets/ws) and [@types/ws](https://www.npmjs.com/package/@types/ws) into `server/package.json`
* remove `zmqConectionString: ZMQ_CONNECTION_STRING,` from API info response (which has `/` url): not sure we should expose it anyway and it doesn't make sense since analytics connects to hastic server over http (same port as the API)
* remove from config `ZMQ_IPC_PATH`, `ZMQ_DEV_PORT`, `ZMQ_HOST` vars
* no `ZMQ_IPC_PATH` folder creation in `data_service.ts`
* no `npm rebuild zeromq` in node 6.14 build process
* server sends error if second instance of analytics tries to connect
* add [transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread) for transpiling the ws lib for node, [read more about that](https://github.com/babel/babel-loader/issues/170)

### Analytics
* add dependency to [aaugustin/websockets](https://github.com/aaugustin/websockets) in `analytics/requrements.txt`
* remove `ZMQ_DEV_PORT` and `ZMQ_CONNECTION_STRING` and replace it with `HASTIC_SERVER_URL`

## Notes
* we still use `pyzmq` for messaging between threads/actors, see `AsyncZmqThread`
* I encourage all supporters of this part to read comment in https://github.com/aaugustin/websockets/blob/master/src/websockets/client.py#L313 (and give a star to https://github.com/aaugustin/websockets)
* Give a star to https://github.com/websockets/ws
* Maybe we should send a webhock about bad analytic connect attempts
* there are optional deps to https://github.com/websockets/bufferutil and `utf-8-validate` which I don't know what to do with. 
* **the minumum supported version for the dev mode is 8.3.0** now. It's because of https://github.com/websockets/ws/issues/1703 (we don't use `babel-loader` in the dev mode)

## Known issues
* reconnecting in analytics to server on drop increases the number of ThreadPoolExecutor

### CODE REVIEW

**Comment by rozetko** [comment]
Tried to test it, but failed. There are at least 2 problems:

- Connection to analytics drops when learning starts.
Server logs after I click "Apply" in the panel:
```
Analytics is up
LEARNING started for abfcc8T9ZoRSrXpl
query time range: from Wed Feb 19 2020 13:41:32 GMT+0300 (MSK) to Wed Feb 19 2020 19:41:32 GMT+0300 (MSK)
run LEARN task, id:abfcc8T9ZoRSrXpl
Analytics is down
(node:4427) UnhandledPromiseRejectionWarning: Can`t send because analytics is not connected
(node:4427) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

- Learning starts though, this is what I see in analytics' logs when learning is finished:
```
2020-02-19 19:45:41,385 [Analytics] [DEBUG]  End correctly handle_analytic_task with anatytic unit: abfcc8T9ZoRSrXpl
2020-02-19 19:45:41,386 [Analytics] [ERROR]  Task exception was never retrieved
future: <Task finished coro=<ServerService._on_message_to_thread() done, 
defined at bin/../analytics/services/server_service.py:87> exception=AttributeError("'NoneType' object has no attribute 'send'",)>
Traceback (most recent call last):
  File "bin/../analytics/services/server_service.py", line 88, in _on_message_to_thread
    await self.__server_socket.send(message)
AttributeError: 'NoneType' object has no attribute 'send'
```

Tested with 2 node versions:
```bash
python3.6 --version
Python 3.6.7

node -v
v11.15.0
```

```bash
python3.6 --version
Python 3.6.7

node -v
v8.16.0
```

**Comment by jonyrock-back** [comment]
@rozetko was it dev mode or prod build?

**Comment by rozetko** [comment]
@jonyrock-back dev

**Comment by jonyrock-back** [comment]
Looks like I have this issue here: https://github.com/babel/babel-loader/issues/170

**Comment by rozetko** [comment]
More logs from analytics:

```
2020-03-04 20:57:30,477 [Analytics] [DEBUG]  client - event = eof_received()
2020-03-04 20:57:30,534 [Analytics] [DEBUG]  Start handle_analytic_task with analytic unit: nv3eCrznaqm2yhJ6
2020-03-04 20:57:30,536 [Analytics] [DEBUG]  client - event = connection_lost(None)
2020-03-04 20:57:30,536 [Analytics] [DEBUG]  Analytics get task with type: LEARN for unit: nv3eCrznaqm2yhJ6
2020-03-04 20:57:30,537 [Analytics] [DEBUG]  client - state = CLOSED
2020-03-04 20:57:30,553 [Analytics] [DEBUG]  client x code = 1005, reason = [no reason]
2020-03-04 20:57:30,558 [Analytics] [DEBUG]  Start method fit for analytic unit nv3eCrznaqm2yhJ6
2020-03-04 20:57:30,587 [Analytics] [ERROR]  Task exception was never retrieved
future: <Task finished coro=<ServerService._on_message_to_thread() done, 
defined at bin/../analytics/services/server_service.py:87> exception=ConnectionClosedError('code = 1005 (no status code [internal]), no reason',)>Traceback (most recent call last):
  File "bin/../analytics/services/server_service.py", line 88, in _on_message_to_thread
    await self.__server_socket.send(message)
  File "/home/rozetko/.local/lib/python3.6/site-packages/websockets/protocol.py", line 555, in send
    await self.ensure_open()
  File "/home/rozetko/.local/lib/python3.6/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1005 (no status code 
[internal]), no reason
```

**Pull request merged**
